### ISSUE TITLE
Custom adapter supporting requirejs-glob

### ISSUE THREAD

**Issue by Iristyle** [OpenWebStack/gruntacular#6]
So I think it would be interesting to provide a custom adapter that can make use of `requirejs` and `requirejs-glob`.

Testacular doesn't use Connect (yet) -- so not sure how the `glob!` urls would be resolved.
See https://github.com/testacular/testacular/issues/105 for a little more info.

It might just be easiest to pass off the single r.js concatenated file to Testacular, but tossing this out there to see if it's viable or not.

**Comment by geddski** [comment]
I like that idea, it would come in handy if you had a mix of AMD and scripts. What we did in the Structure project was just load all the JS files **except** main.js, so that there's nothing async about it. Check it out: https://github.com/OpenWebStack/structure/blob/master/config/testacular.conf.js

**Comment by geddski** [comment]
I'm marking requirejs-glob as experimental and not going to do much with it. Closing this issue, thanks for your input!
