### ISSUE TITLE
On fail the task crashes

### ISSUE THREAD

**Issue by jperl** [OpenWebStack/gruntacular#7]
I have my grunt file setup to run `testacular:test:run` after a watch.

Everything works perfectly unless a test fails upon which both terminal programs (gruntacular and grunt watch) terminate.

Is there a way to prevent gruntacular from terminating on a test failure?

**Comment by geddski** [comment]
@jperl I added the grunt-watch task to test for this, I'm not seeing it terminate on failing tests. Could you share a sample test that is causing the issue?

**Comment by jperl** [comment]
@geddesign You can reproduce it by cloning [this](https://github.com/jperl/yo-angular-jquery-mobile) and following "Run testacular and keep it open" then trigger the tests to run by making a change and saving it (add a blank line to appUiSpec).

If that is too complicated I could try and reproduce it on this project.

**Comment by geddski** [comment]
Should be fixed in 0.3.0. Thanks for the good catch. Let me know if you still have troubles with it.
